name: movie_db_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  go_router: ^14.8.0
  flutter_launcher_icons: ^0.14.3
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  formz: ^0.8.0
  intl: ^0.20.2
  shared_preferences: ^2.4.0
  animate_do: ^3.3.7
  card_swiper: ^3.0.1
  dio: ^5.8.0+1
  flutter_staggered_grid_view: ^0.7.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/

